apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: core-dns-sample-service
  labels:
    # any Pods with matching labels are included in this Deployment
    app: external-svc-poc
    tier: core-dns-sample-service
spec:
  # ReplicaSet specification
  replicas: 3
  selector:
    matchLabels:
      # ReplicaSet labels will match Pods with the following labels
      tier: core-dns-sample-service
  template:
    metadata:
      labels:
        # Pod's labels
        app: external-svc-poc
        tier: core-dns-sample-service
    spec:
      containers:
        - name: communication-container
          image: core-dns-sample:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
