apiVersion: v1
kind: Service
metadata:
  name: my-external-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ExternalName
  externalName: affinipay.com
  selector:
    app: external-service-poc
