apiVersion: v1
kind: Service
metadata:
  name: core-dns-sample-external
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ExternalName
  externalName: astros.com
  selector:
    app: external-svc-poc
